fix dev-build

diff --git a/.github/workflows/dev-build.yml b/.github/workflows/dev-build.yml
--- a/.github/workflows/dev-build.yml
+++ b/.github/workflows/dev-build.yml
@@ -23,10 +23,10 @@ jobs:
       - uses: actions/checkout@v3
       - name: Load VERSION
         run: |
-          if [ -f VERSION ]; then
-            echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
+          if [ -f DEV-VERSION ]; then
+            echo "VERSION=$(cat DEV-VERSION)" >> $GITHUB_ENV
           else
-            echo "VERSION file not found!" && exit 1
+            echo "DEV-VERSION file not found!" && exit 1
           fi
       - name: Set up Go
         uses: actions/setup-go@v3
@@ -68,10 +68,10 @@ jobs:
         uses: actions/checkout@v4
       - name: Load VERSION
         run: |
-          if [ -f VERSION ]; then
-            echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
+          if [ -f DEV-VERSION ]; then
+            echo "VERSION=$(cat DEV-VERSION)" >> $GITHUB_ENV
           else
-            echo "VERSION file not found!" && exit 1
+            echo "DEV-VERSION file not found!" && exit 1
           fi
 
       - name: Set up QEMU
@@ -94,4 +94,4 @@ jobs:
           push: true
           tags: | 
             ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-            ${{ env.IMAGE_NAME }}:latest
+            ${{ env.IMAGE_NAME }}:dev
